### ISSUE TITLE
Maya node does not exist 'mia_physicalsky1'

### ISSUE THREAD

**Issue by jiangwh93** [maciejgryka/shadow-gen#1]
Hi,

I'm new in maya and PyMel, and I am trying to reimplement the result in deshadowing, described in the article "Learning to Remove Soft Shadows". 

When I was using the built-in python script module in maya to run create_scene.py, an error occured. The description of this error is listed below:

# Error: line 1: MayaNodeError: file /Applications/Autodesk/maya2015/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/pymel/core/general.py line 2069: Maya Node does not exist (or is not unique):: u'mia_physicalsky1' # 

I tried to run this code in both maya 2017 and maya 2015 which support mental ray renderer, both of them popped out the exactly same error.

I also have tried adding the 'mia-physicalsky1' node manually in node editor, but still not working.

Looking forward to some constructive advices.

BR.

**Comment by maciejgryka** [comment]
Hey @jiangwh93! The only thing I would suggest is making sure you name the node `mia_physicalsky1` (with an underscore `_` instead of a hyphen `-`). It does seem like the script relies on the `mia_physicalsky1` object to be present - as far as I can remember it was there in the `scene.mb` file that the script assumes present. Unfortunately, I don't have that file around anymore.

Alternatively you can try removing those lines from the script and then adding the sky manually if you need it.

Thanks for your interest - I wish I was able to help more!
